# Generated by Django 4.1 on 2022-09-12 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='criacao',
            new_name='criado',
        ),
    ]
